service: dynamo-serverless
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource:
            - !GetAtt Products.Arn

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"
    target: node20
    platform: node

functions:
  listProducts:
    handler: src/functions/listProducts.handler
    events:
      - httpApi:
          path: /products
          method: get
  getProduct:
    handler: src/functions/getProduct.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  createProduct:
    handler: src/functions/createProduct.handler
    events:
      - httpApi:
          path: /products
          method: post
  updateProduct:
    handler: src/functions/updateProduct.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: put
  deleteProduct:
    handler: src/functions/deleteProduct.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: delete

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
